/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import firmadigital.Archivo;
import firmadigital.FirmaDigital;
import java.io.File;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author user1
 */
public class Ventana extends javax.swing.JFrame {
    private PrivateKey llavePrivada;
    private PublicKey llavePublica;
    private String rutaLlavePrivada, rutaLlavePublica, rutaArchivo;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JTabbedPane();
        panelFirma = new javax.swing.JPanel();
        btnFirmaArchivo = new javax.swing.JButton();
        btnFirmaLlave = new javax.swing.JButton();
        lblFirmaArchivoRuta = new javax.swing.JLabel();
        lblFirmaLlaveRuta = new javax.swing.JLabel();
        btnFirmar = new javax.swing.JButton();
        panelVerificacion = new javax.swing.JPanel();
        btnVerifArchivo = new javax.swing.JButton();
        lblVerifArchivoRuta = new javax.swing.JLabel();
        btnVerifLlave = new javax.swing.JButton();
        lblVerifLlaveRuta = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFirmaArchivo.setText("Archivo");
        btnFirmaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmaArchivoActionPerformed(evt);
            }
        });

        btnFirmaLlave.setText("Llave privada");
        btnFirmaLlave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmaLlaveActionPerformed(evt);
            }
        });

        lblFirmaArchivoRuta.setText("Ningún archivo seleccionado...");

        lblFirmaLlaveRuta.setText("Ningún archivo seleccionado...");

        btnFirmar.setText("FIRMAR");
        btnFirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFirmaLayout = new javax.swing.GroupLayout(panelFirma);
        panelFirma.setLayout(panelFirmaLayout);
        panelFirmaLayout.setHorizontalGroup(
            panelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFirmaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFirmaLlave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFirmaArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirmaArchivoRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFirmaLayout.createSequentialGroup()
                        .addComponent(lblFirmaLlaveRuta)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFirmaLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(btnFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        panelFirmaLayout.setVerticalGroup(
            panelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFirmaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirmaArchivo)
                    .addComponent(lblFirmaArchivoRuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirmaLlave)
                    .addComponent(lblFirmaLlaveRuta))
                .addGap(30, 30, 30)
                .addComponent(btnFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        panelPrincipal.addTab("Firmar", panelFirma);

        btnVerifArchivo.setText("Archivo");
        btnVerifArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifArchivoActionPerformed(evt);
            }
        });

        lblVerifArchivoRuta.setText("Ningún archivo seleccionado...");

        btnVerifLlave.setText("Llave publica");
        btnVerifLlave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifLlaveActionPerformed(evt);
            }
        });

        lblVerifLlaveRuta.setText("Ningún archivo seleccionado...");

        btnVerificar.setText("VERIFICAR");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVerificacionLayout = new javax.swing.GroupLayout(panelVerificacion);
        panelVerificacion.setLayout(panelVerificacionLayout);
        panelVerificacionLayout.setHorizontalGroup(
            panelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerificacionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVerifLlave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerifArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVerifArchivoRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVerificacionLayout.createSequentialGroup()
                        .addComponent(lblVerifLlaveRuta)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerificacionLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        panelVerificacionLayout.setVerticalGroup(
            panelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerificacionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerifArchivo)
                    .addComponent(lblVerifArchivoRuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerifLlave)
                    .addComponent(lblVerifLlaveRuta))
                .addGap(30, 30, 30)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        panelPrincipal.addTab("Verificar", panelVerificacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirmaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmaArchivoActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 2);
        if (rutaArchivo != null) {
            lblFirmaArchivoRuta.setText(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnFirmaArchivoActionPerformed

    private void btnFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarActionPerformed
        // TODO add your handling code here:
        FirmaDigital fd = new FirmaDigital();
        Archivo archivo = new Archivo(rutaArchivo);
        String informacion = archivo.getInfo();
        byte[] cifrado;
        cifrado = fd.firmar(informacion, llavePrivada);
        String a = new String(cifrado, StandardCharsets.UTF_8);
        archivo.saveBytes("Firmado.txt", cifrado);
        JOptionPane.showMessageDialog(null, "Archivo firmado exitosamente");
    }//GEN-LAST:event_btnFirmarActionPerformed

    private void btnVerifArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifArchivoActionPerformed
        abrirArchivo((byte) 2);
        if (rutaArchivo != null) {
            lblVerifArchivoRuta.setText(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnVerifArchivoActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
         FirmaDigital fd = new FirmaDigital();
        Archivo archivo = new Archivo(rutaArchivo);
        try {
            if (fd.verificar(archivo.getBytes(), llavePublica)) {
                JOptionPane.showMessageDialog(null, "Firma verificada correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Firma incorrecta");
            }
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnFirmaLlaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmaLlaveActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 0);
        if (rutaLlavePrivada != null) {
            Archivo archivo = new Archivo(rutaLlavePrivada);
            lblFirmaLlaveRuta.setText(rutaLlavePrivada);
            llavePrivada = (PrivateKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnFirmaLlaveActionPerformed

    private void btnVerifLlaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifLlaveActionPerformed
        // TODO add your handling code here:
        abrirArchivo((byte) 1);
        if (rutaLlavePublica != null) {
            Archivo archivo = new Archivo(rutaLlavePublica);
            lblVerifLlaveRuta.setText(rutaLlavePublica);
            llavePublica = (PublicKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnVerifLlaveActionPerformed

     private void abrirArchivo(int opcion) {
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File abre = file.getSelectedFile();
        switch (opcion) {
            case 0:
                rutaLlavePrivada = abre != null ? abre.getAbsolutePath() : null;
                break;
            case 1:
                rutaLlavePublica = abre != null ? abre.getAbsolutePath() : null;
                break;
            case 2:
                rutaArchivo = abre != null ? abre.getAbsolutePath() : null;
                break;
        }
    }

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirmaArchivo;
    private javax.swing.JButton btnFirmaLlave;
    private javax.swing.JButton btnFirmar;
    private javax.swing.JButton btnVerifArchivo;
    private javax.swing.JButton btnVerifLlave;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFirmaArchivoRuta;
    private javax.swing.JLabel lblFirmaLlaveRuta;
    private javax.swing.JLabel lblVerifArchivoRuta;
    private javax.swing.JLabel lblVerifLlaveRuta;
    private javax.swing.JPanel panelFirma;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JPanel panelVerificacion;
    // End of variables declaration//GEN-END:variables
}
